import React, { useState, useEffect } from 'react';

const SlideThumbnail = ({ slide, index }) => (
  <div className="border dark:border-gray-700 rounded-md p-3 aspect-[16/9] flex flex-col justify-center items-center bg-gray-100 dark:bg-gray-800">
    <p className="text-xs text-gray-500">Slide {index + 1}</p>
    <p className="font-semibold text-center text-sm">{slide.title}</p>
  </div>
);

export default function DeckPreviewPanel({ aiPlanId }) {
  const [deck, setDeck] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!aiPlanId) return;
    setLoading(true);
    const interval = setInterval(() => {
      fetch(`/api/campaign/decks/${aiPlanId}`)
        .then(res => res.json())
        .then(data => {
          if (data) {
            setDeck(data);
            setLoading(false);
            clearInterval(interval);
          }
        });
    }, 3000); // Poll every 3 seconds

    return () => clearInterval(interval);
  }, [aiPlanId]);

  if (loading) {
    return (
      <div className="p-6 text-center">
        <p>Your pitch deck is being generated by the AI...</p>
        <p className="text-sm text-gray-500">This may take a moment.</p>
      </div>
    );
  }

  if (!deck) {
    return <div className="p-6 text-center">No deck has been generated for this plan yet.</div>;
  }

  return (
    <div className="p-8 bg-white dark:bg-gray-900 rounded-lg shadow-lg">
      <header className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold">AI-Generated Pitch Deck</h2>
          <p className="text-sm text-gray-500">A full campaign proposal, ready to present.</p>
        </div>
        <div className="flex gap-2">
          <a href={deck.pdfUrl} target="_blank" rel="noreferrer" className="px-4 py-2 text-sm font-medium border rounded-md">Download PDF</a>
          <a href={deck.pptxUrl} target="_blank" rel="noreferrer" className="px-4 py-2 text-sm font-medium border rounded-md">Download PPTX</a>
        </div>
      </header>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {(deck.jsonSlides || []).map((slide, index) => (
          <SlideThumbnail key={index} slide={slide} index={index} />
        ))}
      </div>

      <footer className="mt-6 flex justify-end">
        <button className="px-4 py-2 text-sm font-semibold text-white bg-blue-600 rounded-md">
          Auto-Send to Brand
        </button>
      </footer>
    </div>
  );
}