import OpenAI from "openai";
import prisma from "../lib/prisma.js";
import { sendSlackAlert } from "../integrations/slack/slackClient.js";
import { safeEnv } from "../utils/safeEnv.js";

const OPENAI_API_KEY = safeEnv("OPENAI_API_KEY", "");
const OPENAI_MODEL = safeEnv("OPENAI_MODEL", "gpt-4o-mini");
const client = OPENAI_API_KEY ? new OpenAI({ apiKey: OPENAI_API_KEY }) : null;

type NegotiationResult = {
  fair_market_value?: number;
  suggested_counter_offer?: number;
  confidence?: number;
  negotiation_rationale?: string;
  risk_factors?: string[];
  suggested_email_reply?: string;
  summary?: string;
};

export async function generateNegotiationAdvice(dealId: string, userId: string) {
  const deal = await prisma.dealThread.findUnique({
    where: { id: dealId },
    include: { brand: true, emails: true, events: true }
  });

  if (!deal) throw new Error("Deal not found");

  const prompt = `You are an elite talent manager and negotiator. Using the provided deal data, return JSON ONLY with keys: fair_market_value (number), suggested_counter_offer (number), confidence (0-1), negotiation_rationale (string), risk_factors (array), suggested_email_reply (string), summary (string, 4-6 sentences). Avoid legal advice; stay within provided facts.\n\nDeal data:\n${JSON.stringify(
    deal,
    null,
    2
  )}`;

  if (!client) {
    const fallback: NegotiationResult = {
      fair_market_value: 0,
      suggested_counter_offer: 0,
      confidence: 0.1,
      negotiation_rationale: "OpenAI key missing; manual negotiation required.",
      risk_factors: [],
      suggested_email_reply: "Hi, let's review deliverables and budgets before confirming.",
      summary: "AI key missing. Provide manual negotiation overview."
    };
    await persistResult(dealId, userId, fallback);
    return fallback;
  }

  const response = await client.chat.completions.create({
    model: OPENAI_MODEL || "gpt-4o-mini",
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: "You are an expert influencer deal negotiator." },
      { role: "user", content: prompt }
    ],
    temperature: 0.25
  });

  const content = response.choices?.[0]?.message?.content;
  if (!content) throw new Error("Empty AI response");
  const data: NegotiationResult = JSON.parse(content);

  await persistResult(dealId, userId, data);

  if ((data.confidence ?? 1) < 0.3) {
    await sendSlackAlert("⚠️ Low-confidence deal analysis", { dealId });
  }

  return data;
}

async function persistResult(dealId: string, userId: string, data: NegotiationResult) {
  await prisma.dealThread.update({
    where: { id: dealId },
    data: { negotiationInsights: data as any }
  });

  await prisma.dealEvent.create({
    data: {
      dealId,
      actorId: userId,
      type: "NEGOTIATION_ADVICE",
      message: "AUTO: Negotiation advice generated by AI",
      metadata: data as any
    }
  });
}
