#!/bin/bash
# Quick setup script for production environment variables
# Copy these values into your hosting platform dashboard

echo "================================"
echo "FRONTEND (Vercel) ENV VARS"
echo "================================"
echo ""
echo "VITE_API_URL=https://api.tbctbctbc.online/api"
echo ""
echo "================================"
echo "BACKEND (Railway) ENV VARS"
echo "================================"
echo ""
echo "NODE_ENV=production"
echo "FRONTEND_ORIGIN=https://tbctbctbc.online"
echo "WEB_APP_URL=https://tbctbctbc.online"
echo "COOKIE_DOMAIN=.tbctbctbc.online"
echo "USE_HTTPS=true"
echo "API_URL=https://api.tbctbctbc.online"
echo ""
echo "# Keep existing values for these:"
echo "# DATABASE_URL=<from Neon>"
echo "# JWT_SECRET=<your secret>"
echo "# RESEND_API_KEY=<from Resend>"
echo "# GOOGLE_CLIENT_ID=<from Google Console>"
echo "# GOOGLE_CLIENT_SECRET=<from Google Console>"
echo "# GOOGLE_REDIRECT_URI=https://api.tbctbctbc.online/api/auth/google/callback"
echo ""
echo "================================"
echo "After setting these, redeploy both frontend and backend!"
echo "================================"
