ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "location" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "timezone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pronouns" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "accountType" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "socialLinks" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingComplete" BOOLEAN DEFAULT false;
