-- This migration was skipped because the database already contains most of these tables
-- and enums from previous migrations. Creating them again would cause conflicts.
-- The schema is already in sync via the sequence of previous migrations.
